CREATE DATABASE sts2web;

CREATE USER sts2web WITH PASSWORD '비밀번호';

GRANT ALL PRIVILEGES ON DATABASE sts2web TO sts2web;

GRANT ALL ON SCHEMA public TO sts2web;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO sts2web;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO sts2web;
